entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  traefik:           # Add this entrypoint for the dashboard
    address: ":8080"

api:
  dashboard: true     # Already good
  insecure: true      # Add this to allow access without authentication (for testing)

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: "im.aufa.ai@gmail.com"
      storage: "/data/acme.json"
      tlsChallenge: {}
