FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY projects.json /usr/share/nginx/html/
COPY script.js /tmp/script.js
RUN apk add --no-cache gettext && \
    echo "API_KEY=$API_KEY" > /tmp/env.debug && \
    if [ -z "$API_KEY" ]; then echo "Error: API_KEY is not set" >> /tmp/env.debug; exit 1; fi && \
    envsubst '${API_KEY}' < /tmp/script.js > /usr/share/nginx/html/script.js && \
    rm /tmp/script.js
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]