FROM nginx:alpine

# Copy all the static assets to the nginx html directory
COPY index.html /usr/share/nginx/html/
COPY projects.json /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
